name: Validar ESModules

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  esm-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependÃªncias
        run: npm install

      - name: Validar imports ESModules
        run: node --experimental-modules src/monitor.js
